filename: None # Filename of data file, str 
time_taken: True # Plot time taken for calculation to complete 
colors: None # A list of colours for different vacuum sizes - if using hex codes put '' around them, list
width: 6 # Width of figure in inches, float
height: 5 # Height of figure in inches, float
dpi: 300 # dots per inch, int 
heatmap: False # Plots a heatmap of surface energies 
cmap: wistia # Matplotlib colormap 
plt_fname: energy_per_atom.png # Name of the plot, str 