start: None # Filename of initial structure file, str 
end: None # Filename of final structure if comparing, str
ox_states: None # Add oxidation states to the bulk structure by guess by default, can also add as dict or list 
save_csv: True # Save csv or print to terminal
csv_fname: nn_data.csv # Name of the csv file, str